baseURL = "https://radreads.github.io/hugo-blog/"
languageCode = "en-us"
title = "Meet Khe Hy"
enableRobotsTXT = true

[pagination]
  pagerSize = 7

[params]
  description = "Entrepreneur, Coach and Writer" 